# Uncomment the next line to define a global platform for your project
  platform :ios, '8.0'

target 'iPhone-ObjectiveC-Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iPhone-ObjectiveC-Demo
  # pod 'OpenCV', '~>4.1.0'
  pod 'OpenCV', :path => './OpenCV' #指定podspec文件
end
